# config.toml

[mqttms.mqtt]
host = "broker.emqx.io"                     # MQTT brokr URI
port = 1883                                 # port
username = ""                               # username if must log in
password = ""                               # password if must log in
client_id = "client_394578"                 # client ID. Must be uinq for earch smartfan installation
timeout = 30.0                              # timeout in second to wait for reaction (on connection request, subscription etc)
long_payload = 25                           # payload lenth threshod. Used in logging.

[mqttms.ms]
client_uuid = "e6f87d77-4216-4be1-ab83-b5fa6792b747"    # Used as identifier of this application running on concrete computer
server_uuid = "f93e3068-40d5-45ba-b221-8dd6faa596dd"    # UUID of DUT    e8a5106c-9b8b-4040-b906-bbc466d2bc1f
cmd_topic = "@/server_uuid/CMD/format"       # template of MS protocol command topic
timeout = 5.0

[[mqttms.ms.subs_topics]]
topic = "@/server_uuid/RSP/format"
format = "ASCIIHEX"

[[mqttms.ms.subs_topics]]
topic = "@/server_uuid/USL/format"
format = "JSON"

[logging]
verbose = 3
log_prefix = true
use_color = true
use_string_handler = false

[dut]
ident = "150360"                # identifier of DUT brand
name = "Smart Ventilator"       # Human readable name
serial_date = "2606"            # year and moth or production
serialn = "0000001"             # serial number
serial_separator = "-"          # separator between parts of the serial number

[tests]
motoron = 3.0           # time to maintain motor in ON state in tests
motoroff = 1.0          # time to maintain motor in OFF state in tests
heateron = 2.0          # time to maintain heater in ON state in tests
ionizeron = 2.0         # time to maintain ionizer in ON state in tests
repelleron = 2.0        # time to maintain ultra repeller in ON state in tests
buttontime = 10.0       # time to wait for user to press the local button and IR remote control button
amb_thr = 750           # ambient threshold between light and dark (the lesser the darker)
amb_low = 0             # reasonable lowest value
amb_high = 4095         # reasonable highest value
co_thr = 9              # CO sensor threshold
co_low = 0              # reasonable lowest value
co_high = 1200          # reasonable highest value
temp_thr = 2300         # temperature threshold
temp_low = 0            # reasonable lowest value
temp_high = 4500        # reasonable highest value
press_thr = 95000       # air pressure threshold (not used)
press_low = 60000       # reasonable lowest value
press_high = 110000     # reasonable highest value
hum_thr = 75000         # air humidity threshold
hum_low = 0             # reasonable lowest value
hum_high = 100000       # reasonable highest value
air_thr = 16000         # air quality threshold
air_low = 500           # reasonable lowest value
air_high = 100000       # reasonable highest value

[options]
mode = "testbench"      # select operational mode ("testbench", "snonly", "monitor")
monitor_delay = 2.0     # interval to refresh data
monitor_loops = 10      # how many loops to execute monitor. 0 means endless
dutdelay = 2.0          # Delay in seconds after DIT BLE pairing
interactive = true      # if false, smartfan uses values from the configuration or options and do not ask at command line for conformation
pairing = true          # Use BLE pairing.
resetwifi = false       # Do not reset Wifinf at the end of the tests.
stop_if_failed = true   # stop testing if some test fails.