# definitions/api_commands.py

from enum import StrEnum

class ApiCmd(StrEnum):
    WHO_AM_I = "WH"
    NOP = "NP"
    SENSORS = "SR"
    WIFICRED = "WF"
    SET_MODE = "MD"
    GET_SMAC = "GM"
    SET_AMB_THR = "AH"
    SET_CO_THR = "CH"
    SET_HUM_THR = "HH"
    SET_GAS_THR = "GH"
    SET_TEMP_THR = "TH"
    SENSORS_ENABLE = "SE"
    OUTPUTS_ENABLE = "OE"
    POSTVENTTIME = "PT"
    POSTLIGHTTIME = "PL"
    CO_INTERVAL = "CI"
    AUTO_TIMES = "AT"
    SET_PHASES = "FX"
    SET_SPEED = "SX"
    LED_DUTY = "LD"
    GET_PARAMS = "PG"
    LOGS = "LG"
    MQTT_READY = "MQ"
    SETMQTT = "SQ"
    RESTART = "RS"
    VERSION = "VS"
    SERIAL = "SN"
    OUTPUT = "OU"
    FAN = "FA"
    FAN_PHASE = "FF"
    FAN_PROCESS = "FP"
    LEDS = "LE"
    RESET = "RE"
    OTA_UPDATE = "OT"
    OTA_VERSION_ONLY = "OV"
    SETBASEURL = "SB"
    TIMEZONE = "TZ"
    CMD_INVALID = "--"
